### ISSUE TITLE
根本没有效果

### ISSUE THREAD

**Issue by zhangqian19910223** [ltym2016/FilterTabView#2]
你只给出了最简单的效果，展示的效果都是假的，项目里没有

**Comment by kdsrsl** [comment]
是全的，在MainActivity里注掉了，解开之后是6个。

作者做的demo还是挺全的，除了有错别字 筛选在我测试机有bug 没有横向的分组 不是我要找的效果之外，其他都挺好的。。。。

**Comment by ltym2016** [comment]
> 是全的，在MainActivity里注掉了，解开之后是6个。
> 
> 作者做的demo还是挺全的，除了有错别字筛选在我测试机有虫没有横向的分组不是我要找的效果之外，其他都挺好的....

什么样的bug可以提一下吗？我这边修改一下

**Comment by ltym2016** [comment]
> 你只给出了最简单的效果，展示的效果都是假的，项目里没有

**Comment by ltym2016** [comment]
> 你只给出了最简单的效果，展示的效果都是假的，项目里没有

需要你将MainActivity里注释掉的代码放开，我这边是为来测试注释掉了
